name: Develop Branch Semantic Release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://npm.pkg.github.com/"

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Get latest release version
        id: get_release
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create version.json
        run: |
          echo "{\"version\": \"${RELEASE_VERSION}\"}" > public/version.json
